/*
*@商品组件
*/
(function(){
	// 创建组件对象
	var shopComponents={};
	shopComponents.shop_component_one='<div class="compentent_container"><ul class="shop_component_one"><div class="btn_top">+</div><div class="btn_down">+</div><div class="clear">x</div><li class="container_one"><div class="shop_img_one"><img src="https://img.yzcdn.cn/upload_files/2018/03/13/0c3606ee96756b5b67dce937a3345023.png"></div><div class="text_message_one"><div><h3>此处显示商品</h3><p style="font-size:12px">此处显示商品描述</p></div><div class="price_one clearfloat"><span>￥999.00</span><i></i></div></div> <div class="icon_one"><i>+</i></div></li></ul></div>';
	shopComponents.shop_component_two='<div class="compentent_container"><div class="shop_component_two"><div class="btn_top">+</div><div class="btn_down">+</div><div class="clear">x</div><ul class="container"><li class="container_two"><a href="#"><div class="shop_img_two"><img src="https://img.yzcdn.cn/upload_files/2018/03/13/0c3606ee96756b5b67dce937a3345023.png"><div class="surper_script_two"><i>*</i></div></div><div class="text_message_two"><h3 class="title">此处显示商品</h3><div class="price_two  clearfloat"><span>￥999.00</span ><i class="cart_btn_two">+</i></div></div></a></li><li class="container_two"><a href="#"><div class="shop_img_two"><img src="https://img.yzcdn.cn/upload_files/2018/03/13/0c3606ee96756b5b67dce937a3345023.png"><div class="surper_script_two"><i>*</i></div></div><div class="text_message_two"><h3 class="title">此处显示商品</h3><div class="price_two  clearfloat"><span>￥999.00</span ><i class="cart_btn_two">+</i></div></div></a></li></ul></div></div>';
	shopComponents.shop_component_three='<div class="compentent_container"><div class="shop_component_three"><div class="btn_top">+</div><div class="btn_down">+</div><div class="clear">x</div><ul class="container"><li class="container_three_one"><div class="shop_img_three_one"><img src="https://img.yzcdn.cn/upload_files/2018/03/13/0c3606ee96756b5b67dce937a3345023.png"></div><div class="text_message_three_one"><div><h3>此处显示商品</h3><p style="font-size:12px">此处显示商品描述</p></div><div class="price_three_one clearfloat"><span>￥999.00</span><i></i></div></div><div class="icon_three_one"><i>+</i></div></li><li class="container_three_two"><a href="#"><div class="shop_img_three_two"><img src="https://img.yzcdn.cn/upload_files/2018/03/13/0c3606ee96756b5b67dce937a3345023.png"><div class="surper_script_three_two"><i>*</i></div></div><div class="text_message_three_two"><h3 class="title">此处显示商品</h3><div class="price_three_two  clearfloat"><span>￥999.00</span ><i class="cart_btn_three_two">+</i></div></div></a></li><li class="container_three_two"><a href="#"><div class="shop_img_three_two"><img src="https://img.yzcdn.cn/upload_files/2018/03/13/0c3606ee96756b5b67dce937a3345023.png"><div class="surper_script_three_two"><i>*</i></div></div><div class="text_message_three_two"><h3 class="title">此处显示商品</h3><div class="price_three_two  clearfloat"><span>￥999.00</span ><i class="cart_btn_three_two">+</i></div></div></a></li></ul></div></div>';
	shopComponents.shop_component_four='<div class="compentent_container"><div class="shop_component_four"><div class="btn_top">+</div><div class="btn_down">+</div><div class="clear">x</div><ul class="container"><li class="container_four"><a href="#"><div class="shop_img_four"><img src="https://img.yzcdn.cn/upload_files/2018/03/13/0c3606ee96756b5b67dce937a3345023.png"><div class="surper_script_four"><i>*</i></div></div><div class="text_message_four"><h3 class="title_four">此处显示商品</h3><p class="sub_title_four">此处显示商品描述</p><p class="price_four"><em>￥999.00</em><span>+</span></p></div></a></li><li class="container_four"><a href="#"><div class="shop_img_four"><img src="https://img.yzcdn.cn/upload_files/2018/03/13/0c3606ee96756b5b67dce937a3345023.png"><div class="surper_script_four"><i>*</i></div></div><div class="text_message_four"><h3 class="title_four">此处显示商品</h3><p class="sub_title_four">此处显示商品描述</p><p class="price_four"><em>￥999.00</em><span>+</span></p></div></a></li><li class="container_four"><a href="#"><div class="shop_img_four"><img src="https://img.yzcdn.cn/upload_files/2018/03/13/0c3606ee96756b5b67dce937a3345023.png"><div class="surper_script_four"><i>*</i></div></div><div class="text_message_four"><h3 class="title_four">此处显示商品</h3><p class="sub_title_four">此处显示商品描述</p><p class="price_four"><em>￥999.00</em><span>+</span></p></div></a></li></ul></div></div>';
	shopComponents.shop_component_five='<div class="compentent_container"><div class="shop_component_five"><div class="btn_top">+</div><div class="btn_down">+</div><div class="clear">x</div><ul class="container"><li class="container_five"><a href="#"><div class="shop_img_five"><img src="https://img.yzcdn.cn/upload_files/2018/03/13/0c3606ee96756b5b67dce937a3345023.png"><div class="surper_script_five"><i>*</i></div></div><div class="text_message_five"><h3 class="title_five">此处显示商品名称</h3><p class="price_five"><em>￥999.00</em><span>+</span></p></div></a></li><li class="container_five"><a href="#"><div class="shop_img_five"><img src="https://img.yzcdn.cn/upload_files/2018/03/13/0c3606ee96756b5b67dce937a3345023.png"><div class="surper_script_five"><i>*</i></div></div><div class="text_message_five"><h3 class="title_five">此处显示商品名称</h3><p class="price_five"><em>￥999.00</em><span>+</span></p></div></a></li><li class="container_five"><a href="#"><div class="shop_img_five"><img src="https://img.yzcdn.cn/upload_files/2018/03/13/0c3606ee96756b5b67dce937a3345023.png"><div class="surper_script_five"><i>*</i></div></div><div class="text_message_five"><h3 class="title_five">此处显示商品名称</h3><p class="price_five"><em>￥999.00</em><span>+</span></p></div></a></li><li class="container_five"><a href="#"><div class="shop_img_five"><img src="https://img.yzcdn.cn/upload_files/2018/03/13/0c3606ee96756b5b67dce937a3345023.png"><div class="surper_script_five"><i>*</i></div></div><div class="text_message_five"><h3 class="title_five">此处显示商品名称</h3><p class="price_five"><em>￥999.00</em><span>+</span></p></div></a></li></ul></div></div>';
	shopComponents.shop_component_six='<div class="compentent_container"><div class="shop_component_six"><div class="btn_top">+</div><div class="btn_down">+</div><div class="clear">x</div><div class="container"><ul class="shop_component_six_container"><li class="container_six"><a href="#"><div class="shop_img_six"><img src="https://img.yzcdn.cn/upload_files/2018/03/13/0c3606ee96756b5b67dce937a3345023.png"><div class="surper_script_six"><i>*</i></div></div><div class="text_message_six"><h3 class="title_six">此处显示商品名称</h3><p class="price_six"><em>￥999.00</em><span>+</span></p></div></a></li><li class="container_six"><a href="#"><div class="shop_img_six"><img src="https://img.yzcdn.cn/upload_files/2018/03/13/0c3606ee96756b5b67dce937a3345023.png"><div class="surper_script_six"><i>*</i></div></div><div class="text_message_six"><h3 class="title_six">此处显示商品名称</h3><p class="price_six"><em>￥999.00</em><span>+</span></p></div></a></li><li class="container_six"><a href="#"><div class="shop_img_six"><img src="https://img.yzcdn.cn/upload_files/2018/03/13/0c3606ee96756b5b67dce937a3345023.png"><div class="surper_script_six"><i>*</i></div></div><div class="text_message_six"><h3 class="title_six">此处显示商品名称</h3><p class="price_six"><em>￥999.00</em><span>+</span></p></div></a></li><li class="container_six"><a href="#"><div class="shop_img_six"><img src="https://img.yzcdn.cn/upload_files/2018/03/13/0c3606ee96756b5b67dce937a3345023.png"><div class="surper_script_six"><i>*</i></div></div><div class="text_message_six"><h3 class="title_six">此处显示商品名称</h3><p class="price_six"><em>￥999.00</em><span>+</span></p></div></a></li></ul></div></div></div>';
	shopComponents.shop_groups_compontent_one='<div class="content_container"><ul class="content_container_list"><li><a><div class="img_container"><img src="https://img.yzcdn.cn/public_files/2018/01/30/585dae8447d80013ef9344adc973c6ee.png?imageView2/2/w/730/h/0/q/75/format/webp"></div><div class="message_container"><h3 class="title">此处显示商品</h3><p class="sub_title">此处显示商品描述</p><p class="price"><em>￥999.00</em></p></div><div class="shop_btn"><i class="btn_icon">@</i></div></a></li><li><a><div class="img_container"><img src="https://img.yzcdn.cn/public_files/2018/01/30/585dae8447d80013ef9344adc973c6ee.png?imageView2/2/w/730/h/0/q/75/format/webp"></div><div class="message_container"><h3 class="title">此处显示商品</h3><p class="sub_title">此处显示商品描述</p><p class="price"><em>￥999.00</em></p></div><div class="shop_btn"><i class="btn_icon">@</i></div></a></li><li><a><div class="img_container"><img src="https://img.yzcdn.cn/public_files/2018/01/30/585dae8447d80013ef9344adc973c6ee.png?imageView2/2/w/730/h/0/q/75/format/webp"></div><div class="message_container"><h3 class="title">此处显示商品</h3><p class="sub_title">此处显示商品描述</p><p class="price"><em>￥999.00</em></p></div><div class="shop_btn"><i class="btn_icon">@</i></div></a></li></ul></div>'
	shopComponents.shop_groups_compontent_two='<div class="content_container"><ul class="content_container_list_small"><li class="content_container_list_small_list"><a><div class="img_container_small"><img src="https://img.yzcdn.cn/public_files/2018/01/30/585dae8447d80013ef9344adc973c6ee.png?imageView2/2/w/730/h/0/q/75/format/webp"></div><div class="message_container_small"><h3 class="title">此处显示商品</h3><p class="sub_title">此处显示商品描述</p><p class="price"><em>￥999.00</em></p></div><div class="shop_btn"><i class="btn_icon">@</i></div></a></li><li class="content_container_list_small_list"><a><div class="img_container_small"><img src="https://img.yzcdn.cn/public_files/2018/01/30/585dae8447d80013ef9344adc973c6ee.png?imageView2/2/w/730/h/0/q/75/format/webp"></div><div class="message_container_small"><h3 class="title">此处显示商品</h3><p class="sub_title">此处显示商品描述</p><p class="price"><em>￥999.00</em></p></div><div class="shop_btn"><i class="btn_icon">@</i></div></a></li><li class="content_container_list_small_list"><a><div class="img_container_small"><img src="https://img.yzcdn.cn/public_files/2018/01/30/585dae8447d80013ef9344adc973c6ee.png?imageView2/2/w/730/h/0/q/75/format/webp"></div><div class="message_container_small"><h3 class="title">此处显示商品</h3><p class="sub_title">此处显示商品描述</p><p class="price"><em>￥999.00</em></p></div><div class="shop_btn"><i class="btn_icon">@</i></div></a></li><li class="content_container_list_small_list"><a><div class="img_container_small"><img src="https://img.yzcdn.cn/public_files/2018/01/30/585dae8447d80013ef9344adc973c6ee.png?imageView2/2/w/730/h/0/q/75/format/webp"></div><div class="message_container_small"><h3 class="title">此处显示商品</h3><p class="sub_title">此处显示商品描述</p><p class="price"><em>￥999.00</em></p></div><div class="shop_btn"><i class="btn_icon">@</i></div></a></li> </ul></div>'
	shopComponents.shop_groups_compontent_three='<div class="content_container"><ul class="content_container_list_small_and_big"><li class="content_container_list_small_and_big_list"><a><div class="img_container_big"><img src="https://img.yzcdn.cn/public_files/2018/01/30/585dae8447d80013ef9344adc973c6ee.png?imageView2/2/w/730/h/0/q/75/format/webp"></div><div class="message_container_big"><h3 class="title">此处显示商品</h3><p class="sub_title">此处显示商品描述</p><p class="price"><em>￥999.00</em></p></div><div class="shop_btn"><i class="btn_icon">@</i></div></a></li><li class="content_container_list_small_list"><a><div class="img_container_small"><img src="https://img.yzcdn.cn/public_files/2018/01/30/585dae8447d80013ef9344adc973c6ee.png?imageView2/2/w/730/h/0/q/75/format/webp"></div><div class="message_container_small"><h3 class="title">此处显示商品</h3><p class="sub_title">此处显示商品描述</p><p class="price"><em>￥999.00</em></p></div><div class="shop_btn"><i class="btn_icon">@</i></div></a></li><li class="content_container_list_small_list"><a><div class="img_container_small"><img src="https://img.yzcdn.cn/public_files/2018/01/30/585dae8447d80013ef9344adc973c6ee.png?imageView2/2/w/730/h/0/q/75/format/webp"></div><div class="message_container_small"><h3 class="title">此处显示商品</h3><p class="sub_title">此处显示商品描述</p><p class="price"><em>￥999.00</em></p></div><div class="shop_btn"><i class="btn_icon">@</i></div></a></li></ul></div>';
	shopComponents.shop_groups_compontent_four='<div class="content_container"><ul class="content_container_list_detail"><li class="content_container_list_detail_list"><a class="clearfloat"><div class="img_container_detail"><img src="https://img.yzcdn.cn/public_files/2018/01/30/585dae8447d80013ef9344adc973c6ee.png?imageView2/2/w/730/h/0/q/75/format/webp"></div><div class="message_container_detail"><h3 class="title_detail">此处显示商品</h3><p class="sub_title_detail">此处显示商品描述</p><p class="price_detail"><em>￥999.00</em></p></div><div class="shop_btn"><i class="btn_icon">@</i></div></a></li><li class="content_container_list_detail_list"><a class="clearfloat"><div class="img_container_detail"><img src="https://img.yzcdn.cn/public_files/2018/01/30/585dae8447d80013ef9344adc973c6ee.png?imageView2/2/w/730/h/0/q/75/format/webp"></div><div class="message_container_detail"><h3 class="title_detail">此处显示商品</h3><p class="sub_title_detail">此处显示商品描述</p><p class="price_detail"><em>￥999.00</em></p></div><div class="shop_btn"><i class="btn_icon">@</i></div></a></li><li class="content_container_list_detail_list"><a class="clearfloat"><div class="img_container_detail"><img src="https://img.yzcdn.cn/public_files/2018/01/30/585dae8447d80013ef9344adc973c6ee.png?imageView2/2/w/730/h/0/q/75/format/webp"></div><div class="message_container_detail"><h3 class="title_detail">此处显示商品</h3><p class="sub_title_detail">此处显示商品描述</p><p class="price_detail"><em>￥999.00</em></p></div><div class="shop_btn"><i class="btn_icon">@</i></div></a></li></ul></div>';
	shopComponents.shop_groups_compontent_five=' <div class="content_container"><ul class="content_container_list_oneThree clearfloat"><li class="content_container_list_detail_oneThree"><a class="clearfloat"><div class="img_container_oneThree"><img src="https://img.yzcdn.cn/public_files/2018/01/30/585dae8447d80013ef9344adc973c6ee.png?imageView2/2/w/730/h/0/q/75/format/webp</li><li class="content_container_list_detail_oneThree"><a class="clearfloat"><div class="img_container_oneThree"><img src="https://img.yzcdn.cn/public_files/2018/01/30/585dae8447d80013ef9344adc973c6ee.png?imageView2/2/w/730/h/0/q/75/format/webp"></div><div class="message_container_oneThree"><h3 class="title_detail">此处显示商品</h3><p class="sub_title_detail">此处显示商品描述</p><p class="price_oneThree"><em>￥999.00</em></p></div><div class="shop_btn shop_btn_oneThree "><i class="btn_icon btn_icon_oneThree" >@</i></div></a></li><li class="content_container_list_detail_oneThree"><a class="clearfloat"><div class="img_container_oneThree"><img src="https://img.yzcdn.cn/public_files/2018/01/30/585dae8447d80013ef9344adc973c6ee.png?imageView2/2/w/730/h/0/q/75/format/webp"></div><div class="message_container_oneThree"><h3 class="title_detail">此处显示商品</h3><p class="sub_title_detail">此处显示商品描述</p><p class="price_oneThree"><em>￥999.00</em></p></div><div class="shop_btn shop_btn_oneThree "><i class="btn_icon btn_icon_oneThree" >@</i></div></a></li><li class="content_container_list_detail_oneThree"><a class="clearfloat"><div class="img_container_oneThree"><img src="https://img.yzcdn.cn/public_files/2018/01/30/585dae8447d80013ef9344adc973c6ee.png?imageView2/2/w/730/h/0/q/75/format/webp"></div><div class="message_container_oneThree"><h3 class="title_detail">此处显示商品</h3><p class="sub_title_detail">此处显示商品描述</p><p class="price_oneThree"><em>￥999.00</em></p></div><div class="shop_btn shop_btn_oneThree "><i class="btn_icon btn_icon_oneThree" >@</i></div></a></li></ul></div>';
	shopComponents.shop_groups_compontent_six=' <div class="content_container"><ul class="content_container_list_slide clearfloat"><li class="content_container_list_detail_slide"><a class="clearfloat"><div class="img_container_slide"><img src="https://img.yzcdn.cn/public_files/2018/01/30/585dae8447d80013ef9344adc973c6ee.png?imageView2/2/w/730/h/0/q/75/format/webp"></div><div class="message_container_slide"><h3 class="title_slide">此处显示商品</h3><p class="sub_title_slide">此处显示商品描述</p><p class="price_slide"><em>￥999.00</em></p></div><div class="shop_btn shop_btn_slide "><i class="btn_icon btn_icon_slide" >+</i></div></a></li><li class="content_container_list_detail_slide"><a class="clearfloat"><div class="img_container_slide"><img src="https://img.yzcdn.cn/public_files/2018/01/30/585dae8447d80013ef9344adc973c6ee.png?imageView2/2/w/730/h/0/q/75/format/webp"></div><div class="message_container_slide"><h3 class="title_slide">此处显示商品</h3><p class="sub_title_slide">此处显示商品描述</p><p class="price_slide"><em>￥999.00</em></p></div><div class="shop_btn shop_btn_slide "><i class="btn_icon btn_icon_slide" >+</i></div></a></li><li class="content_container_list_detail_slide"><a class="clearfloat"><div class="img_container_slide"><img src="https://img.yzcdn.cn/public_files/2018/01/30/585dae8447d80013ef9344adc973c6ee.png?imageView2/2/w/730/h/0/q/75/format/webp"></div><div class="message_container_slide"><h3 class="title_slide">此处显示商品</h3><p class="sub_title_slide">此处显示商品描述</p><p class="price_slide"><em>￥999.00</em></p></div><div class="shop_btn shop_btn_slide "><i class="btn_icon btn_icon_slide" >+</i></div></a></li><li class="content_container_list_detail_slide"><a class="clearfloat"><div class="img_container_slide"><img src="https://img.yzcdn.cn/public_files/2018/01/30/585dae8447d80013ef9344adc973c6ee.png?imageView2/2/w/730/h/0/q/75/format/webp"></div><div class="message_container_slide"><h3 class="title_slide">此处显示商品</h3><p class="sub_title_slide">此处显示商品描述</p><p class="price_slide"><em>￥999.00</em></p></div><div class="shop_btn shop_btn_slide "><i class="btn_icon btn_icon_slide" >+</i></div></a></li></ul></div>';
	shopComponents.shop_groups_compontent_seven=' <div class="design_compontent_tag_list_preview"><div class="cap_taglist"><div class="cap_taglist_nav"><a class="hairline selected" href="#">商品组一</a><a class="hairline" href="#">商品组二</a><a class="hairline" href="#">商品组三</a><a class="hairline" href="#">商品组四</a></div><div class="cap_taglist_group"><div><div class="cap_taglist_group_title">商品组一</div><div class="cap_taglist_group_card" style="border:none"><div class="cap_taglist_thumb"><img src="https://img.yzcdn.cn/public_files/2018/01/30/585dae8447d80013ef9344adc973c6ee.png?imageView2/2/w/730/h/0/q/75/format/webp"></div><h2 class="cap_tagest_title">此处显示商品名称</h2><div class="cap_tagest_price"><span>￥</span><span>1.50</span></div><div class="cap_tagest_icon_add">+</div></div><div class="cap_taglist_group_card"><div class="cap_taglist_thumb"><img src="https://img.yzcdn.cn/public_files/2018/01/30/585dae8447d80013ef9344adc973c6ee.png?imageView2/2/w/730/h/0/q/75/format/webp"></div><h2 class="cap_tagest_title">此处显示商品名称</h2><div class="cap_tagest_price"><span>￥</span><span>1.50</span></div><div class="cap_tagest_icon_add">+</div></div></div></div><div class="cap_taglist_group"><div><div class="cap_taglist_group_title">商品组一</div><div class="cap_taglist_group_card" style="border:none"><div class="cap_taglist_thumb"><img src="https://img.yzcdn.cn/public_files/2018/01/30/585dae8447d80013ef9344adc973c6ee.png?imageView2/2/w/730/h/0/q/75/format/webp"></div><h2 class="cap_tagest_title">此处显示商品名称</h2><div class="cap_tagest_price"><span>￥</span><span>1.50</span></div><div class="cap_tagest_icon_add">+</div></div><div class="cap_taglist_group_card"><div class="cap_taglist_thumb"><img src="https://img.yzcdn.cn/public_files/2018/01/30/585dae8447d80013ef9344adc973c6ee.png?imageView2/2/w/730/h/0/q/75/format/webp"></div><h2 class="cap_tagest_title">此处显示商品名称</h2><div class="cap_tagest_price"><span>￥</span><span>1.50</span></div><div class="cap_tagest_icon_add">+</div></div></div></div></div></div>';
	//添加组件 【向父节点添加html，关键字（insertAdjacentHTML，'afterBegin'）】
	// var compentent_container=document.querySelector(".compentent_container");
	// compentent_container.insertAdjacentHTML('afterBegin',shopComponents.shop_component_six);
	
	// 添加组件方法;
	// shopComponents.addNode=function(fatherNodeName,btnType,childNodes){
	// 	var FatherNodeName=document.querySelector(fatherNodeName);
	// 	FatherNodeName.insertAdjacentHTML(btnType,childNodes);

	// }

	// shopComponents.addNode(".compentent_container",'afterBegin',shopComponents.shop_component_six);
    // shopComponents.addNode(".compentent_container",'beforeend',shopComponents.shop_component_two);
	// shopComponents.addNode(".compentent_container",'beforeend',shopComponents.shop_component_two);
	// shopComponents.addNode(".compentent_container",'afterBegin',shopComponents.shop_component_three);
	// shopComponents.addNode(".compentent_container",'afterBegin',shopComponents.shop_component_four);
	// shopComponents.addNode(".compentent_container",'afterBegin',shopComponents.shop_component_five);
// 鼠标移入移出


// 	shopComponents.mouse=function(nodeName,btn1,btn2,clear){
// 		var nodeName=document.querySelector(nodeName);
// 		console.log(nodeName);
// 		var btn1=document.querySelector(btn1);
// 		var btn2=document.querySelector(btn2);
// 		var clear=document.querySelector(clear);
// 		nodeName.onmousemove=function(event){
// 			nodeName.style.borderLeft = '1px dashed blue';
// 			nodeName.style.borderRight = '1px dashed blue';
// 			nodeName.style.borderTop = '1px solid blue';
// 			nodeName.style.borderBottom = '1px solid blue';
// 			btn1.style.display="block";
// 			btn2.style.display="block";
// 			clear.style.display="block";
// 		}
// 		nodeName.onmouseout=function(event){
// 			btn1.style.display="none";
// 			btn2.style.display="none";
// 			clear.style.display="none";
// 			nodeName.style.borderLeft = '1px dashed white';
// 			nodeName.style.borderRight = '1px dashed white';
// 			nodeName.style.borderTop = '1px solid white';
// 			nodeName.style.borderBottom = '1px solid white';
// 			// nodeName.style.zIndex="100";
// 		}
// 	}

// shopComponents.mouse(".shop_component_two",".btn_top",".btn_down",".clear");

// shopComponents.mouse(".shop_component_three",".btn_top",".btn_down",".clear");
// shopComponents.mouse(".shop_component_four",".btn_top",".btn_down",".clear");
// shopComponents.mouse(".shop_component_five",".btn_top",".btn_down",".clear");
// shopComponents.mouse(".shop_component_six",".btn_top",".btn_down",".clear");
//添加和移出功能

window.shopComponents=shopComponents;
})();

