/*
*@商品组件
*/
(function(){
	// 创建组件对象
	var shopComponents={};
	shopComponents.shop_component_one='<ul class="shop_component_one"><li class="container_one"><div class="shop_img_one"><img src="https://img.yzcdn.cn/upload_files/2018/03/13/0c3606ee96756b5b67dce937a3345023.png"></div><div class="text_message_one"><div><h3>此处显示商品</h3><p style="font-size:12px">此处显示商品描述</p></div><div class="price_one clearfloat"><span>￥999.00</span><i></i></div></div> <div class="icon_one"><i>+</i></div></li></ul>';
	shopComponents.shop_component_two='<ul class="shop_component_two"><li class="container_two"><a href="#"><div class="shop_img_two"><img src="https://img.yzcdn.cn/upload_files/2018/03/13/0c3606ee96756b5b67dce937a3345023.png"><div class="surper_script_two"><i>*</i></div></div><div class="text_message_two"><h3 class="title">此处显示商品</h3><div class="price_two  clearfloat"><span>￥999.00</span ><i class="cart_btn_two">+</i></div></div></a></li><li class="container_two"><a href="#"><div class="shop_img_two"><img src="https://img.yzcdn.cn/upload_files/2018/03/13/0c3606ee96756b5b67dce937a3345023.png"><div class="surper_script_two"><i>*</i></div></div><div class="text_message_two"><h3 class="title">此处显示商品</h3><div class="price_two  clearfloat"><span>￥999.00</span ><i class="cart_btn_two">+</i></div></div></a></li></ul>';
	shopComponents.shop_component_three='<ul class="shop_component_three"><li class="container_three_one"><div class="shop_img_three_one"><img src="https://img.yzcdn.cn/upload_files/2018/03/13/0c3606ee96756b5b67dce937a3345023.png"></div><div class="text_message_three_one"><div><h3>此处显示商品</h3><p style="font-size:12px">此处显示商品描述</p></div><div class="price_three_one clearfloat"><span>￥999.00</span><i></i></div></div><div class="icon_three_one"><i>+</i></div></li><li class="container_three_two"><a href="#"><div class="shop_img_three_two"><img src="https://img.yzcdn.cn/upload_files/2018/03/13/0c3606ee96756b5b67dce937a3345023.png"><div class="surper_script_three_two"><i>*</i></div></div><div class="text_message_three_two"><h3 class="title">此处显示商品</h3><div class="price_three_two  clearfloat"><span>￥999.00</span ><i class="cart_btn_three_two">+</i></div></div></a></li><li class="container_three_two"><a href="#"><div class="shop_img_three_two"><img src="https://img.yzcdn.cn/upload_files/2018/03/13/0c3606ee96756b5b67dce937a3345023.png"><div class="surper_script_three_two"><i>*</i></div></div><div class="text_message_three_two"><h3 class="title">此处显示商品</h3><div class="price_three_two  clearfloat"><span>￥999.00</span ><i class="cart_btn_three_two">+</i></div></div></a></li></ul>';
	shopComponents.shop_component_four='<ul class="shop_component_four"><li class="container_four"><a href="#"><div class="shop_img_four"><img src="https://img.yzcdn.cn/upload_files/2018/03/13/0c3606ee96756b5b67dce937a3345023.png"><div class="surper_script_four"><i>*</i></div></div><div class="text_message_four"><h3 class="title_four">此处显示商品</h3><p class="sub_title_four">此处显示商品描述</p><p class="price_four"><em>￥999.00</em><span>+</span></p></div></a></li><li class="container_four"><a href="#"><div class="shop_img_four"><img src="https://img.yzcdn.cn/upload_files/2018/03/13/0c3606ee96756b5b67dce937a3345023.png"><div class="surper_script_four"><i>*</i></div></div><div class="text_message_four"><h3 class="title_four">此处显示商品</h3><p class="sub_title_four">此处显示商品描述</p><p class="price_four"><em>￥999.00</em><span>+</span></p></div></a></li><li class="container_four"><a href="#"><div class="shop_img_four"><img src="https://img.yzcdn.cn/upload_files/2018/03/13/0c3606ee96756b5b67dce937a3345023.png"><div class="surper_script_four"><i>*</i></div></div><div class="text_message_four"><h3 class="title_four">此处显示商品</h3><p class="sub_title_four">此处显示商品描述</p><p class="price_four"><em>￥999.00</em><span>+</span></p></div></a></li></ul>';
	shopComponents.shop_component_five='   <ul class="shop_component_five"><li class="container_five"><a href="#"><div class="shop_img_five"><img src="https://img.yzcdn.cn/upload_files/2018/03/13/0c3606ee96756b5b67dce937a3345023.png"><div class="surper_script_five"><i>*</i></div></div><div class="text_message_five"><h3 class="title_five">此处显示商品名称</h3><p class="price_five"><em>￥999.00</em><span>+</span></p></div></a></li><li class="container_five"><a href="#"><div class="shop_img_five"><img src="https://img.yzcdn.cn/upload_files/2018/03/13/0c3606ee96756b5b67dce937a3345023.png"><div class="surper_script_five"><i>*</i></div></div><div class="text_message_five"><h3 class="title_five">此处显示商品名称</h3><p class="price_five"><em>￥999.00</em><span>+</span></p></div></a></li><li class="container_five"><a href="#"><div class="shop_img_five"><img src="https://img.yzcdn.cn/upload_files/2018/03/13/0c3606ee96756b5b67dce937a3345023.png"><div class="surper_script_five"><i>*</i></div></div><div class="text_message_five"><h3 class="title_five">此处显示商品名称</h3><p class="price_five"><em>￥999.00</em><span>+</span></p></div></a></li><li class="container_five"><a href="#"><div class="shop_img_five"><img src="https://img.yzcdn.cn/upload_files/2018/03/13/0c3606ee96756b5b67dce937a3345023.png"><div class="surper_script_five"><i>*</i></div></div><div class="text_message_five"><h3 class="title_five">此处显示商品名称</h3><p class="price_five"><em>￥999.00</em><span>+</span></p></div></a></li></ul>';
	shopComponents.shop_component_six='<div class="shop_component_six"><ul class="shop_component_six_container"><li class="container_six"><a href="#"><div class="shop_img_six"><img src="https://img.yzcdn.cn/upload_files/2018/03/13/0c3606ee96756b5b67dce937a3345023.png"><div class="surper_script_six"><i>*</i></div></div><div class="text_message_six"><h3 class="title_six">此处显示商品名称</h3><p class="price_six"><em>￥999.00</em><span>+</span></p></div></a></li><li class="container_six"><a href="#"><div class="shop_img_six"><img src="https://img.yzcdn.cn/upload_files/2018/03/13/0c3606ee96756b5b67dce937a3345023.png"><div class="surper_script_six"><i>*</i></div></div><div class="text_message_six"><h3 class="title_six">此处显示商品名称</h3><p class="price_six"><em>￥999.00</em><span>+</span></p></div></a></li><li class="container_six"><a href="#"><div class="shop_img_six"><img src="https://img.yzcdn.cn/upload_files/2018/03/13/0c3606ee96756b5b67dce937a3345023.png"><div class="surper_script_six"><i>*</i></div></div><div class="text_message_six"><h3 class="title_six">此处显示商品名称</h3><p class="price_six"><em>￥999.00</em><span>+</span></p></div></a></li><li class="container_six"><a href="#"><div class="shop_img_six"><img src="https://img.yzcdn.cn/upload_files/2018/03/13/0c3606ee96756b5b67dce937a3345023.png"><div class="surper_script_six"><i>*</i></div></div><div class="text_message_six"><h3 class="title_six">此处显示商品名称</h3><p class="price_six"><em>￥999.00</em><span>+</span></p></div></a></li></ul></div>';

	//添加组件 
	var compentent_container=document.querySelector(".compentent_container");
	compentent_container.innerHTML=shopComponents.shop_component_six;
	// shop.innerHTML=shopComponents.shop_component_two;

	function Setting(shopSource,listStyle,fillWay,showSize,showStyle,showContent,btnStyle,userDefined){
	this.shopSource=shopSource;
	this.listStyle=listStyle;
	this.fillWay=fillWay;
	this.showSize=showSize;
	this.showStyle=showStyle;
	this.showContent=showContent;
	this.btnStyle=btnStyle;
	this.userDefined=userDefined;
	this.switch=function(){
		console.log("nishi"+shopSource+listStyle)
	}
}

window.Setting=Setting;
})();

